### ISSUE TITLE
[greasemonkey] icon is 404 now

### ISSUE THREAD

**Issue by FranklinYu** [warren-bank/crx-googlesource-raw-format#2]
This icon https://opensource.google.com/assets/static/images/favicon.png is removed upstream. I’m not sure what’s a good replacement; the best I can find is:

![Google Open Source logo](https://4.bp.blogspot.com/-rRU93x3zbZI/WNUsVIWX9gI/AAAAAAAABEE/znl5dRud0jUvq9aEEi9nyKNapCTvuExZwCLcB/s1600/logo.png)

The original icon was also archived at [the Wayback Machine](https://web.archive.org/web/20220202023338/https://opensource.google/assets/static/images/favicon.png).

**Comment by warren-bank** [comment]
Thanks for letting me know; I'll push an update shortly.

Here's the image source URL that looks least likely to change..

```text
view-source:https://opensource.google/
  contains:
    <link rel="manifest" href="/_pwa/opensource/manifest.json" crossorigin="use-credentials">

https://opensource.google/_pwa/opensource/manifest.json
  contains:
    relative links to several sizes of the icon

https://opensource.google/_pwa/opensource/icons/icon-96x96.png
  96px
```
